# Generated by Django 2.1.3 on 2019-02-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20190210_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracklike',
            old_name='creator',
            new_name='user',
        ),
    ]
