# Generated by Django 2.1.3 on 2019-02-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcelike',
            old_name='creator',
            new_name='user',
        ),
    ]
